package com.yuewan.paper.domain;

import java.util.Date;

public class Paper {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.id
     *
     * @mbg.generated Fri Aug 23 14:22:42 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.date
     *
     * @mbg.generated Fri Aug 23 14:22:42 CST 2019
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.g_id
     *
     * @mbg.generated Fri Aug 23 14:22:42 CST 2019
     */
    private Integer gId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.u_id
     *
     * @mbg.generated Fri Aug 23 14:22:42 CST 2019
     */
    private Integer uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.u_name
     *
     * @mbg.generated Fri Aug 23 14:22:42 CST 2019
     */
    private String uName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.status
     *
     * @mbg.generated Fri Aug 23 14:22:42 CST 2019
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.content
     *
     * @mbg.generated Fri Aug 23 14:22:42 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.id
     *
     * @return the value of paper.id
     *
     * @mbg.generated Fri Aug 23 14:22:42 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.id
     *
     * @param id the value for paper.id
     *
     * @mbg.generated Fri Aug 23 14:22:42 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.date
     *
     * @return the value of paper.date
     *
     * @mbg.generated Fri Aug 23 14:22:42 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.date
     *
     * @param date the value for paper.date
     *
     * @mbg.generated Fri Aug 23 14:22:42 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.g_id
     *
     * @return the value of paper.g_id
     *
     * @mbg.generated Fri Aug 23 14:22:42 CST 2019
     */
    public Integer getgId() {
        return gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.g_id
     *
     * @param gId the value for paper.g_id
     *
     * @mbg.generated Fri Aug 23 14:22:42 CST 2019
     */
    public void setgId(Integer gId) {
        this.gId = gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.u_id
     *
     * @return the value of paper.u_id
     *
     * @mbg.generated Fri Aug 23 14:22:42 CST 2019
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.u_id
     *
     * @param uId the value for paper.u_id
     *
     * @mbg.generated Fri Aug 23 14:22:42 CST 2019
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.u_name
     *
     * @return the value of paper.u_name
     *
     * @mbg.generated Fri Aug 23 14:22:42 CST 2019
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.u_name
     *
     * @param uName the value for paper.u_name
     *
     * @mbg.generated Fri Aug 23 14:22:42 CST 2019
     */
    public void setuName(String uName) {
        this.uName = uName == null ? null : uName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.status
     *
     * @return the value of paper.status
     *
     * @mbg.generated Fri Aug 23 14:22:42 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.status
     *
     * @param status the value for paper.status
     *
     * @mbg.generated Fri Aug 23 14:22:42 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.content
     *
     * @return the value of paper.content
     *
     * @mbg.generated Fri Aug 23 14:22:42 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.content
     *
     * @param content the value for paper.content
     *
     * @mbg.generated Fri Aug 23 14:22:42 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}